// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbyaLhE7RLCCqL1UukPtsQhKUqpITkaBJeuY6N7Le_cEfF38yPW-YIWo3OsTaa-34ThZvw/exec";
